;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backspace-whitespace-to-tab-stop
        c-electric-brace
        kill-region
        tab-to-tab-stop
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-mini
        helm-projectile-find-file
        my-select-next
        ))
