

set nocompatible
set number " show line numbers
set showcmd " show me commands as I type them
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set expandtab
set backspace=indent,eol,start
set encoding=utf-8
set ruler " show cursor coordinates
set laststatus=2 " always show statusline
set cursorline " illuminate the cursors current position
set noswapfile
set backupdir=~/.vim/tmp " dump everything in a temp directory
set directory=~/.vim/tmp
set undodir  =~/.vim/tmp
set copyindent
set ttyfast
set incsearch " search as you type, ENTER will accept, ESC will stop
set ignorecase smartcase " ignore case when searching, unless there is an uppercase character
set whichwrap+=<,>,h,l,[,] " make Left and Right movement keys wrap around the ends of lines
set scrolloff=15 " always keep N lines around the cursor
set shortmess+=I " don't show the intro message


" ==================== vim-plug ======================

call plug#begin('~/.vim/plugged')

Plug 'jiangmiao/auto-pairs'     " automatically creates the closing paren, bracket, etc...
Plug 'edsono/vim-matchit'       " allows '%' command to jump between opening/closing HTML tags
Plug 'scrooloose/nerdcommenter' " commenting
" Plug 'chriskempson/base16-vim'
" Plug 'vim-scripts/closetag.vim' " allows 'CTRL-_' to close the currently opened HTML tag
" Plug 'bling/vim-airline'

call plug#end()


" ====================== Colors =======================
set t_Co=256 " enable 256 colors
syntax on
colorscheme custom

" custom colors
hi CursorLine ctermbg=236

" ====================== Controls ======================

" hack, to prevent my ALT key from escaping back to normal mode
let c='a'
while c <= 'z'
    exec "set <A-".c.">=\e".c
    exec "imap \e".c." <A-".c.">"
    let c = nr2char(1+char2nr(c))
endw


imap jj <Esc>

" line swapping
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

" go to next and prev occurences of a word
inoremap <C-d> <C-o>*
inoremap <A-d> <C-o>#

" use F1 to run a normal command from insert mode
" also prevent it from openning the help
nmap <F1> <NOP>
imap <F1> <C-o>
vmap <F1> <NOP>


" In many terminal emulators the mouse works just fine, so I enable it.
if has('mouse')
    set mouse=a
endif


" ====================================================

" be a text editor when you wake up
" also, piss off every VIM user who touches my computer
startinsert

